lib: [
  "_build/install/default/lib/KA_equiv/KA_equiv.a"
  "_build/install/default/lib/KA_equiv/KA_equiv.cma"
  "_build/install/default/lib/KA_equiv/KA_equiv.cmxa"
  "_build/install/default/lib/KA_equiv/META"
  "_build/install/default/lib/KA_equiv/dune-package"
  "_build/install/default/lib/KA_equiv/kA_equiv.cmi"
  "_build/install/default/lib/KA_equiv/kA_equiv.cmt"
  "_build/install/default/lib/KA_equiv/kA_equiv.cmx"
  "_build/install/default/lib/KA_equiv/kA_equiv.ml"
  "_build/install/default/lib/KA_equiv/opam"
]
libexec: [
  "_build/install/default/lib/KA_equiv/KA_equiv.cmxs"
]
bin: [
  "_build/install/default/bin/bench"
]
doc: [
  "_build/install/default/doc/KA_equiv/README.md"
]
